### ISSUE TITLE
Autosave models that are arrays

### ISSUE THREAD

**Issue by jackweinbender** [mitchlloyd/ember-autosave#17]
1.0 has been great, thanks. I was noticing that if, for example, the model contains multiple records (e.g. from `this.store.findAll('xyz')`) setting `xyz: computedAutosave('model', 1000)` doesn't work. This may be by design. The workaround that I've been using is to simply wrap each record in a component, then set the computedAutosave macro there.

Anyway, if it's by design, you may consider adding a line about it to the docs, otherwise, it could be a nice feature.

**Comment by mitchlloyd** [comment]
I don't know if it's exactly "by design", but this library doesn't do much to help you manage arrays of items that might change.

Hopefully you wouldn't need to create components just for the sake of this addon although it's probably the case that you were headed there sooner or later.

For this case you should be able to use the AutosaveProxy object directly:

```javascript
import Ember from 'ember';
import { AutosaveProxy } from 'ember-autosave';
const { computed } = Ember;

export default Ember.Route.extend({
  autosavePosts: computed('posts.[]', function() {
    return this.get('posts').map((post) => AutosaveProxy.create({ content: post }));
  }
});
```

Does this cover your use case? If we find that this is a really common pattern, then it could make sense to document or add some special support in the library.

**Comment by jackweinbender** [comment]
This is a cool solution. The rather obvious problem with my question—it hit me last night—was that, in the situation I described, you would have to call `.save()` on every item in the array anyway.
