### ISSUE TITLE
Issue with general use

### ISSUE THREAD

**Issue by kaylee42** [mitchlloyd/ember-autosave#20]
Hi there! I'm very excited about ember-autosave but am having issues getting it implemented correctly and was hoping for some insight into what's going wrong. I am using Ember 2.3.1 and ember-autosave 1.0.0, and trying to implement it for use with the TinyMCE text editor with a Rails API backend. I'd greatly appreciate any insight or even getting pointed in the right direction. 

I'm calling autosave from the show-sheet component object, but the content is not saving and I'm also not hitting the debugger that I put in the save method: 
```javascript
// app/components/show-sheet.js

import Ember from 'ember';
import autosave from 'ember-autosave';
export default Ember.Component.extend({
  store: Ember.inject.service(),
  sheetProxy: autosave('sheet', {
    save(sheet) {
      debugger;
      sheet.save();
    }
  })
});
```
It's not clear to me what exactly I've done wrong here and why I'm not able to hit the save method. (I also tried replace the last two calls of sheet with `model` and had the same issue - not sure if I'm naming things incorrectly). Here's the component template: 

```handlebars
// app/templates/components/show-sheet.hbs

<div class="col-md-12">
  <h1>{{sheetProxy.title}}</h1>
</div>
<div class="text-editor-wrapper">
    <p style="color:#fff;">.</p>
    {{text-editor value=sheetProxy.content.content }}
</div>
```

`text-editor` is also a component required by TinyMCE, and that looks like this: 

```handlebars
// app/templates/components/text-editor.hbs 

{{textarea value=value}}
```
This last template's syntax is required to remain the same by TinyMCE. I'm wondering if the issue I'm having is that the text area isn't being save because it is in a nested component or that TinyMCE doesn't play well with ember-autosave, or if I've done something else wrong in the setup that is preventing autosave from working? Thanks so much for the help!

**Comment by mitchlloyd** [comment]
Hi Kaylee!

You've hit on a gotcha of [`Ember.ObjectProxy`](http://emberjs.com/api/classes/Ember.ObjectProxy.html) and libraries that use this built in Ember utility. You cannot have a property named `content` on your model because it conflicts with `content` property of the `ObjectProxy`. Inside of your template you have successfully bypassed the proxying behavior that this addon relies on.

```handlebars
{{text-editor value=sheetProxy.content.content }}
```

In the short term, I would consider making an alias for `content` on your model so that it doesn't conflict with this naming. However, I do recognize this is a little lame. I think this library can work without using `Ember.ObjectProxy` so I might take a look at that.

**Comment by kaylee42** [comment]
Ahh, okay - thank you so much!!! I'll try aliasing content and see if I can get things working. :)

**Comment by mitchlloyd** [comment]
I realized that I can't reasonably get rid of reserving `content` without breaking some of [the documented functionality](https://github.com/mitchlloyd/ember-autosave#using-autosaveproxy). I made a todo task to keep track of this and think on it for a next release. I'm closing this for now but let me know if the proposed workaround doesn't work.
